# Generated by Django 5.1 on 2024-09-03 15:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=255)),
                ("index", models.IntegerField()),
                ("phonenumber", models.CharField(max_length=20)),
                ("time", models.DateTimeField(default=django.utils.timezone.now)),
                ("v1", models.CharField(blank=True, max_length=255, null=True)),
                ("v2", models.CharField(blank=True, max_length=255, null=True)),
                ("v3", models.CharField(blank=True, max_length=255, null=True)),
                ("v4", models.CharField(blank=True, max_length=255, null=True)),
                ("v5", models.CharField(blank=True, max_length=255, null=True)),
                ("v6", models.CharField(blank=True, max_length=255, null=True)),
                ("v7", models.CharField(blank=True, max_length=255, null=True)),
                ("v8", models.CharField(blank=True, max_length=255, null=True)),
                ("v9", models.CharField(blank=True, max_length=255, null=True)),
                ("v10", models.CharField(blank=True, max_length=255, null=True)),
                ("v11", models.CharField(blank=True, max_length=255, null=True)),
                ("v12", models.CharField(blank=True, max_length=255, null=True)),
                ("v13", models.CharField(blank=True, max_length=255, null=True)),
                ("v14", models.CharField(blank=True, max_length=255, null=True)),
                ("v15", models.CharField(blank=True, max_length=255, null=True)),
                ("v16", models.CharField(blank=True, max_length=255, null=True)),
                ("v17", models.CharField(blank=True, max_length=255, null=True)),
                ("v18", models.CharField(blank=True, max_length=255, null=True)),
                ("v19", models.CharField(blank=True, max_length=255, null=True)),
                ("v20", models.CharField(blank=True, max_length=255, null=True)),
                ("v21", models.CharField(blank=True, max_length=255, null=True)),
                ("v22", models.CharField(blank=True, max_length=255, null=True)),
                ("v23", models.CharField(blank=True, max_length=255, null=True)),
                ("v24", models.CharField(blank=True, max_length=255, null=True)),
                ("v25", models.CharField(blank=True, max_length=255, null=True)),
                ("v26", models.CharField(blank=True, max_length=255, null=True)),
                ("v27", models.CharField(blank=True, max_length=255, null=True)),
                ("v28", models.CharField(blank=True, max_length=255, null=True)),
                ("amount", models.IntegerField(default=0)),
                (
                    "time_produced",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "time_processed",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("latency", models.IntegerField(default=0)),
                ("prediction", models.IntegerField(default=0)),
                ("reply", models.CharField(default="", max_length=255)),
                ("is_fraud", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feedback_type", models.CharField(max_length=20)),
                ("feedback_response", models.CharField(max_length=20)),
                (
                    "processed_by",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("feedback_timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="adminn.transaction",
                    ),
                ),
            ],
        ),
    ]
